### ISSUE TITLE
USTVGO Streaming Broken!

### ISSUE THREAD

**Issue by deathbybandaid** [fHDHR/fHDHR_USTVGO#101]

**Comment by mlcarson** [comment]
Any idea what the underlying issue is here or if it'll be fixed?

**Comment by deathbybandaid** [comment]
They recently added an api that improved channel gathering and epg, but the current way of retrieving the m3u8 is getting 403 Forbidden

**Comment by deathbybandaid** [comment]
I pushed it through my PIA VPN, and now seems to work

**Comment by mlcarson** [comment]
I must have a different issue.   Most of the channels work for me via a web browser without a VPN -- there are maybe 19 out of the total that require a VPN.  I can't get any of them to work via this app though.

**Comment by deathbybandaid** [comment]
That's the issue I had, they'd work fine in a browser, but if I downloaded the m3u8 file, nogo.
