### ISSUE TITLE
Some Streams may not work under various conditions. Solution: disable channels that don't work for you.

### ISSUE THREAD

**Issue by mlcarson** [fHDHR/fHDHR_USTVGO#119]
45/88 channels work
43/88 channels do not work (videoframe is not found, TunerError: 806 - Tune Failed)
If PIA VPN allows all channels to work then I'd assume that the adblocker feature of it would be the reason.
 
Working:
1: CBS
2: ABC
4: FOX
5: PBS
10: Univision
11: A&E
12: AMC
13: Animal Planet
14: BBC AMerica
15: BET
16: Bravo 
19: CMT
20: Consumer News & Business
21: CNN
22: Comedy Central 
23: Disney Channel
25: DIY
28: E!
29: ESPN
30: ESPN2
32: ESPNU
35: Food 
40: FX Movie
43: Golf
44: GSN
49: HGTV
50: HIST
57: MSNBC
59: NBCSN
62: OWN
64: Paramount
65: POP
68: Science
69: Showtime
72: Starz
74: Sundance
75: Syfy
76: TBS
77: TCM
78: TLC
80: TNT
81: Travel
82: TruTV
86: VH1
87: WE

Not Working:
3: NBC
6: CW
7: MyNetwork
8: ION
9: Telemundo
17: Toon
18: MAX
24: DISXD
26: DLife
27: DISC
31: ESPNC
33: FLIX
34: FNC
36: Freeform
37: Fox1
38: Fox2
39: FX
41: FXX
42: FYI
45: Hall
46: HBO
47: HBO2
48: HBOSIG
51: ID
52: IFC
53: LIFE
54: LMN
55: Lifetime Real Women
56: MMAX
58: MTV
60: NGC
61: NICK
63: Oxygen
66: QVC
67: Reelz
70: Show2
71: Smith
73: StarzEnc
79: The Movie Channel
83: TVGN
84: TVLand
85: USA
88: WGNA

**Comment by deathbybandaid** [comment]
Then use the channel editor to disable those
