### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mikeboxer** [fHDHR/fHDHR_USTVGO#24]
I setup ustvgo but when I go to play a channel, I get the following error:

ConnectionRefusedError: [Errno 111] Connection refused

Any suggestions?

**Comment by deathbybandaid** [comment]
Ignore it, I'm trying to disable the logging of that output, but it comes from using Firefox to scrape the page for the link.

Safebto ignore

**Comment by mikesaho** [comment]
Ok.  I thought that was the reason I can't get anything to play.  I get errors on all streams.

**Comment by deathbybandaid** [comment]
The streams take longer to load than the other fHDHR varients, but they do load

**Comment by deathbybandaid** [comment]
It spits out all kinds of garbage errors and then loads. It's ugly, but in all my testing, it works fine.

**Comment by deathbybandaid** [comment]
Closing, if still an issue, feel free to reopen
