### ISSUE TITLE
USTVGO has no API, and thus, missing Channel Logos: solution within

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_USTVGO#57]
I thought I would mention that there are a bunch of missing/broken icons for USTVGO. Boomarang, Cinemax, Cartoon Network just to name a few. I would get almost half are missing.

**Comment by deathbybandaid** [comment]
migrated this issue to where it goes.

For logos, here's the repo I referenced

https://github.com/fHDHR/fHDHR_Logos

**Comment by deathbybandaid** [comment]
I've also pinned this issue, as it's not something that is easily fixed.

PRs welcome

**Comment by deathbybandaid** [comment]
If you can find an actual api for ustvgo that I haven't found let me know. Right now it's done with page scraping
